services:
  redis:
    image: redis:7-alpine
    container_name: redis
    ports:
      - "6379:6379"
    restart: unless-stopped

  ids:
    image: jasonish/suricata:latest
    container_name: ids
    network_mode: host
    cap_add:
      - NET_ADMIN
      - NET_RAW
      - SYS_NICE
    volumes:
      - ./ids/rules:/var/lib/suricata/rules
    command: ["-i", "lo", "-e"]
    restart: unless-stopped
